export const fa = {
  common: {
    appName: 'نوابانک',
    loading: 'در حال بارگذاری...',
    error: 'خطا',
    success: 'موفق',
    cancel: 'انصراف',
    confirm: 'تایید',
    save: 'ذخیره',
    delete: 'حذف',
    edit: 'ویرایش',
    close: 'بستن',
  },
  currency: {
    toman: 'تومان',
    rial: 'ریال',
    usd: 'دلار',
    eur: 'یورو',
  },
  account: {
    accounts: 'حساب‌ها',
    balance: 'موجودی',
    type: 'نوع',
    cash: 'نقدی',
    bank: 'بانکی',
    wallet: 'کیف پول',
    credit: 'اعتباری',
  },
  bank: {
    banks: 'بانک‌ها',
    name: 'نام بانک',
  },
  auth: {
    login: 'ورود',
    register: 'ثبت نام',
    logout: 'خروج',
    phone: 'شماره موبایل',
    password: 'رمز عبور',
  },
  budget: {
    budget: 'بودجه',
    budgets: 'بودجه‌ها',
    amount: 'مبلغ',
    spent: 'خرج شده',
    remaining: 'باقی مانده',
    exceeded: 'افزایش یافته',
    monthly: 'ماهانه',
    yearly: 'سالیانه',
    weekly: 'هفتگی',
    period: 'دوره',
  },
  goal: {
    goals: 'اهداف',
    goal: 'هدف',
    target: 'هدف',
    progress: 'پیشرفت',
    completed: 'تکمیل شده',
    remaining: 'باقی مانده',
    targetDate: 'تاریخ هدف',
  },
  notification: {
    notifications: 'اعلان‌ها',
    notificationSettings: 'تنظیمات اعلان‌ها',
    budgetAlerts: 'هشدارهای بودجه',
    goalAlerts: 'هشدارهای هدف',
    transactionNotifications: 'اعلان‌های تراکنش',
    transferNotifications: 'اعلان‌های انتقال',
    systemNotifications: 'اعلان‌های سیستم',
    pushNotifications: 'اعلان‌های فشاری',
    investmentGoalMilestone: 'دستاورد هدف سرمایه‌گذاری',
    investmentGoalCompleted: 'هدف سرمایه‌گذاری تکمیل شد',
    portfolioMovement: 'تغییر پرتفوی',
    dividendReceived: 'دریافت سود',
    unrealizedLoss: 'زیان غیرحققی',
    unrealizedGain: 'سود غیرحققی',
  },
  analytics: {
    analytics: 'تحلیل‌ها',
    overview: 'نمای کلی',
    income: 'درآمد',
    expenses: 'هزینه‌ها',
    netCashFlow: 'جریان نقدی خالص',
    trends: 'روندها',
    categories: 'دسته‌بندی‌ها',
    budgetPerformance: 'عملکرد بودجه',
    goalProgress: 'پیشرفت هدف',
  },
   investment: {
     investments: 'سرمایه‌گذاری',
     dashboard: 'داشبورد سرمایه‌گذاری',
     portfolio: 'پرتفوی سرمایه‌گذاری',
     totalValue: 'ارزش کل',
     totalInvested: 'کل سرمایه‌گذاری شده',
     cash: 'نقدین',
     cashBalance: 'موجودی نقدی',
     return: 'بازده',
     returnPercentage: 'درصد بازده',
     holdings: 'مالکیت‌ها',
     asset: 'دارایی',
     quantity: 'مقدار',
     averagePrice: 'قیمت متوسط',
     currentPrice: 'قیمت فعلی',
     marketValue: 'ارزش بازار',
     pl: 'سود/زیان',
     unrealizedPL: 'سود/زیان غیرحققی',
     performance: 'عملکرد',
     allocation: 'تخصیص',
     accounts: 'حساب‌های سرمایه‌گذاری',
     accountNumber: 'شماره حساب',
     broker: 'کارگزاری',
     brokerName: 'نام کارگزاری',
     accountType: 'نوع حساب',
     baseCurrency: 'ارز پایه',
     status: 'وضعیت',
     active: 'فعال',
     suspended: 'معلیق',
     closed: 'بسته',
     transactions: 'تراکنش‌ها',
     transactionType: 'نوع تراکنش',
     fees: 'کارکرد',
     date: 'تاریخ',
     watchlists: 'فهرست‌های نظارت',
     watchlist: 'فهرست نظارت',
     addAsset: 'افزودن دارایی',
     removeAsset: 'حذف دارایی',
     createWatchlist: 'ایجاد فهرست نظارت',
     renameWatchlist: 'تغییر نام فهرست',
     dailyChange: 'تغییر روزانه',
     assetAllocation: 'تخصیص دارایی',
     accountAllocation: 'تخصیص حساب',
     today: 'امروز',
     noHoldings: 'هیچ مالکیتی وجود ندارد',
     noTransactions: 'هیچ تراکنشی وجود ندارد',
     noWatchlists: 'هیچ فهرست نظارتی وجود ندارد',
     dividendReceived: 'سود دریافتی',
     portfolioMovement: 'تغییر پرتفوی',
     significantLoss: 'زیان قابل توجه',
     significantGain: 'سود قابل توجه',
     stock: 'سهام',
     etf: 'صندوق بورسی',
     bond: 'اوراق مشارکت',
     mutualFund: 'صندوق سرمایه‌گذاری',
     crypto: 'رمزارز',
     other: 'سایر',
     symbol: 'نماد',
     exchange: 'بازار',
   },
   payment: {
     payments: 'پرداخت‌ها',
     payment: 'پرداخت',
     beneficiaries: 'ذینفعان',
     beneficiary: 'ذینفع',
     templates: 'قالب‌های پرداخت',
     template: 'قالب پرداخت',
     scheduledPayments: 'پرداخت‌های برنامه‌ریزی شده',
     scheduledPayment: 'پرداخت برنامه‌ریزی شده',
      createPayment: 'ایجاد پرداخت',
      cancelPayment: 'لغو پرداخت',
     createBeneficiary: 'افزودن ذینفع',
     createTemplate: 'ایجاد قالب',
     schedulePayment: 'برنامه‌ریزی پرداخت',
     billPayment: 'پرداخت قبوض',
     topUp: 'شارژ',
     domesticTransfer: 'انتقال داخلی',
     mobileTopup: 'شارژ موبایل',
     charity: 'خیریه',
     destination: 'مقصد',
     destinationType: 'نوع مقصد',
     destinationValue: 'مقدار مقصد',
     destinationName: 'نام مقصد',
     account: 'حساب',
     card: 'کارت',
     mobile: 'موبایل',
     bill: 'قبض',
     amount: 'مبلغ',
     fees: 'کارمزد',
     total: 'مجموع',
     completed: 'تکمیل شده',
     failed: 'ناموفق',
     cancelled: 'لغو شده',
     reversed: 'برگشت داده شده',
     pending: 'در انتظار',
     processing: 'در حال پردازش',
     frequency: 'تکرار',
     daily: 'روزانه',
     weekly: 'هفتگی',
     monthly: 'ماهانه',
     yearly: 'سالیانه',
     nextRunAt: 'اجرای بعدی',
     lastRunAt: 'آخرین اجرا',
     runCount: 'تعداد اجرا',
     maxRuns: 'حداکثر اجرا',
      active: 'فعال',
      paused: 'متوقف',
      isFavorite: 'مورد علاقه',
     bankCode: 'کد بانک',
     bankName: 'نام بانک',
     reference: 'شماره مرجع',
     internalReference: 'شماره مرجع داخلی',
     paymentCompleted: 'پرداخت انجام شد',
     paymentFailed: 'پرداخت ناموفق',
     paymentCancelled: 'پرداخت لغو شد',
     scheduledPaymentFailed: 'پرداخت برنامه‌ریزی شده ناموفق',
   },
};

export const en = {
  common: {
    appName: 'NovaBank',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
  },
  currency: {
    toman: 'Toman',
    rial: 'Rial',
    usd: 'USD',
    eur: 'EUR',
  },
  account: {
    accounts: 'Accounts',
    balance: 'Balance',
    type: 'Type',
    cash: 'Cash',
    bank: 'Bank',
    wallet: 'Wallet',
    credit: 'Credit',
  },
  bank: {
    banks: 'Banks',
    name: 'Bank Name',
  },
  auth: {
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    phone: 'Phone',
    password: 'Password',
  },
  budget: {
    budgets: 'Budgets',
    budget: 'Budget',
    amount: 'Amount',
    spent: 'Spent',
    remaining: 'Remaining',
    exceeded: 'Exceeded',
    monthly: 'Monthly',
    yearly: 'Yearly',
    weekly: 'Weekly',
    period: 'Period',
  },
  goal: {
    goals: 'Goals',
    goal: 'Goal',
    target: 'Target',
    progress: 'Progress',
    completed: 'Completed',
    remaining: 'Remaining',
    targetDate: 'Target Date',
  },
  notification: {
    notifications: 'Notifications',
    notificationSettings: 'Notification Settings',
    budgetAlerts: 'Budget Alerts',
    goalAlerts: 'Goal Alerts',
    transactionNotifications: 'Transaction Notifications',
    transferNotifications: 'Transfer Notifications',
    systemNotifications: 'System Notifications',
    pushNotifications: 'Push Notifications',
    investmentGoalMilestone: 'Investment Goal Milestone',
    investmentGoalCompleted: 'Investment Goal Completed',
    portfolioMovement: 'Portfolio Movement',
    dividendReceived: 'Dividend Received',
    unrealizedLoss: 'Unrealized Loss',
    unrealizedGain: 'Unrealized Gain',
  },
  analytics: {
    analytics: 'Analytics',
    overview: 'Overview',
    income: 'Income',
    expenses: 'Expenses',
    netCashFlow: 'Net Cash Flow',
    trends: 'Trends',
    categories: 'Categories',
    budgetPerformance: 'Budget Performance',
    goalProgress: 'Goal Progress',
  },
   investment: {
     investments: 'Investments',
     dashboard: 'Investment Dashboard',
     portfolio: 'Investment Portfolio',
     totalValue: 'Total Value',
     totalInvested: 'Total Invested',
     cash: 'Cash',
     cashBalance: 'Cash Balance',
     return: 'Return',
     returnPercentage: 'Return %',
     holdings: 'Holdings',
     asset: 'Asset',
     quantity: 'Quantity',
     averagePrice: 'Average Price',
     currentPrice: 'Current Price',
     marketValue: 'Market Value',
     pl: 'P/L',
     unrealizedPL: 'Unrealized P/L',
     performance: 'Performance',
     allocation: 'Allocation',
     accounts: 'Investment Accounts',
     accountNumber: 'Account Number',
     broker: 'Broker',
     brokerName: 'Broker Name',
     accountType: 'Account Type',
     baseCurrency: 'Base Currency',
     status: 'Status',
     active: 'Active',
     suspended: 'Suspended',
     closed: 'Closed',
     transactions: 'Transactions',
     transactionType: 'Transaction Type',
     fees: 'Fees',
     date: 'Date',
     watchlists: 'Watchlists',
     watchlist: 'Watchlist',
     addAsset: 'Add Asset',
     removeAsset: 'Remove Asset',
     createWatchlist: 'Create Watchlist',
     renameWatchlist: 'Rename Watchlist',
     dailyChange: 'Daily Change',
     assetAllocation: 'Asset Allocation',
     accountAllocation: 'Account Allocation',
     today: 'Today',
     noHoldings: 'No holdings found',
     noTransactions: 'No transactions found',
     noWatchlists: 'No watchlists found',
     dividendReceived: 'Dividend Received',
     portfolioMovement: 'Portfolio Movement',
     significantLoss: 'Significant Loss',
     significantGain: 'Significant Gain',
     stock: 'Stock',
     etf: 'ETF',
     bond: 'Bond',
     mutualFund: 'Mutual Fund',
     crypto: 'Crypto',
     other: 'Other',
     symbol: 'Symbol',
     exchange: 'Exchange',
   },
   payment: {
     payments: 'Payments',
     payment: 'Payment',
     beneficiaries: 'Beneficiaries',
     beneficiary: 'Beneficiary',
     templates: 'Payment Templates',
     template: 'Payment Template',
     scheduledPayments: 'Scheduled Payments',
     scheduledPayment: 'Scheduled Payment',
      createPayment: 'Create Payment',
      cancelPayment: 'Cancel Payment',
     createBeneficiary: 'Add Beneficiary',
     createTemplate: 'Create Template',
     schedulePayment: 'Schedule Payment',
     billPayment: 'Bill Payment',
     topUp: 'Top Up',
     domesticTransfer: 'Domestic Transfer',
     mobileTopup: 'Mobile Topup',
     charity: 'Charity',
     destination: 'Destination',
     destinationType: 'Destination Type',
     destinationValue: 'Destination Value',
     destinationName: 'Destination Name',
     account: 'Account',
     card: 'Card',
     mobile: 'Mobile',
     bill: 'Bill',
     amount: 'Amount',
     fees: 'Fees',
     total: 'Total',
     completed: 'Completed',
     failed: 'Failed',
     cancelled: 'Cancelled',
     reversed: 'Reversed',
     pending: 'Pending',
     processing: 'Processing',
     frequency: 'Frequency',
     daily: 'Daily',
     weekly: 'Weekly',
     monthly: 'Monthly',
     yearly: 'Yearly',
     nextRunAt: 'Next Run At',
     lastRunAt: 'Last Run At',
     runCount: 'Run Count',
     maxRuns: 'Max Runs',
      active: 'Active',
      paused: 'Paused',
      isFavorite: 'Favorite',
     bankCode: 'Bank Code',
     bankName: 'Bank Name',
     reference: 'Reference',
     internalReference: 'Internal Reference',
     paymentCompleted: 'Payment completed',
     paymentFailed: 'Payment failed',
     paymentCancelled: 'Payment cancelled',
     scheduledPaymentFailed: 'Scheduled payment failed',
   },
};

export type Locale = 'fa' | 'en';
export type TranslationKeys = typeof fa;
