export const fa = {
  common: {
    appName: 'نوابانک',
    loading: 'در حال بارگذاری...',
    error: 'خطا',
    success: 'موفق',
    cancel: 'انصراف',
    confirm: 'تایید',
    save: 'ذخیره',
    delete: 'حذف',
    edit: 'ویرایش',
    close: 'بستن',
  },
  currency: {
    toman: 'تومان',
    rial: 'ریال',
  },
  account: {
    accounts: 'حساب‌ها',
    balance: 'موجودی',
    type: 'نوع',
    cash: 'نقدی',
    bank: 'بانکی',
    wallet: 'کیف پول',
    credit: 'اعتباری',
  },
  bank: {
    banks: 'بانک‌ها',
    name: 'نام بانک',
  },
  auth: {
    login: 'ورود',
    register: 'ثبت نام',
    logout: 'خروج',
    phone: 'شماره موبایل',
    password: 'رمز عبور',
  },
  budget: {
    budgets: 'بودجه‌ها',
    budget: 'بودجه',
    amount: 'مبلغ',
    spent: 'خرج شده',
    remaining: 'باقی مانده',
    exceeded: 'افزایش یافته',
    monthly: 'ماهانه',
    yearly: 'سالیانه',
    weekly: 'هفتگی',
    period: 'دوره',
  },
  goal: {
    goals: 'اهداف',
    goal: 'هدف',
    target: 'هدف',
    progress: 'پیشرفت',
    completed: 'تکمیل شده',
    remaining: 'باقی مانده',
    targetDate: 'تاریخ هدف',
  },
  analytics: {
    analytics: 'تحلیل‌ها',
    overview: 'نمای کلی',
    income: 'درآمد',
    expenses: 'هزینه‌ها',
    netCashFlow: 'جریان نقدی خالص',
    trends: 'روندها',
    categories: 'دسته‌بندی‌ها',
    budgetPerformance: 'عملکرد بودجه',
    goalProgress: 'پیشرفت هدف',
  },
};

export const en = {
  common: {
    appName: 'NovaBank',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
  },
  currency: {
    toman: 'Toman',
    rial: 'Rial',
  },
  account: {
    accounts: 'Accounts',
    balance: 'Balance',
    type: 'Type',
    cash: 'Cash',
    bank: 'Bank',
    wallet: 'Wallet',
    credit: 'Credit',
  },
  bank: {
    banks: 'Banks',
    name: 'Bank Name',
  },
  auth: {
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    phone: 'Phone',
    password: 'Password',
  },
  budget: {
    budgets: 'Budgets',
    budget: 'Budget',
    amount: 'Amount',
    spent: 'Spent',
    remaining: 'Remaining',
    exceeded: 'Exceeded',
    monthly: 'Monthly',
    yearly: 'Yearly',
    weekly: 'Weekly',
    period: 'Period',
  },
  goal: {
    goals: 'Goals',
    goal: 'Goal',
    target: 'Target',
    progress: 'Progress',
    completed: 'Completed',
    remaining: 'Remaining',
    targetDate: 'Target Date',
  },
  analytics: {
    analytics: 'Analytics',
    overview: 'Overview',
    income: 'Income',
    expenses: 'Expenses',
    netCashFlow: 'Net Cash Flow',
    trends: 'Trends',
    categories: 'Categories',
    budgetPerformance: 'Budget Performance',
    goalProgress: 'Goal Progress',
  },
};

export type Locale = 'fa' | 'en';
export type TranslationKeys = typeof fa;