export const fa = {
  common: {
    appName: 'نوابانک',
    loading: 'در حال بارگذاری...',
    error: 'خطا',
    success: 'موفق',
    cancel: 'انصراف',
    confirm: 'تایید',
    save: 'ذخیره',
    delete: 'حذف',
    edit: 'ویرایش',
    close: 'بستن',
    active: 'فعال',
    cancelled: 'لغو شده',
    createdAt: 'تاریخ ثبت',
    description: 'توضیحات',
  },
  currency: {
    toman: 'تومان',
    rial: 'ریال',
    usd: 'دلار',
    eur: 'یورو',
  },
  account: {
    accounts: 'حساب‌ها',
    balance: 'موجودی',
    type: 'نوع',
    cash: 'نقدی',
    bank: 'بانکی',
    wallet: 'کیف پول',
    credit: 'اعتباری',
  },
  bank: {
    banks: 'بانک‌ها',
    name: 'نام بانک',
  },
  auth: {
    login: 'ورود',
    register: 'ثبت نام',
    logout: 'خروج',
    phone: 'شماره موبایل',
    password: 'رمز عبور',
  },
  budget: {
    budgets: 'بودجه‌ها',
    budget: 'بودجه',
    amount: 'مبلغ',
    spent: 'خرج شده',
    remaining: 'باقی مانده',
    exceeded: 'افزایش یافته',
    monthly: 'ماهانه',
    yearly: 'سالیانه',
    weekly: 'هفتگی',
    period: 'دوره',
  },
  goal: {
    goals: 'اهداف',
    goal: 'هدف',
    target: 'هدف',
    progress: 'پیشرفت',
    completed: 'تکمیل شده',
    remaining: 'باقی مانده',
    targetDate: 'تاریخ هدف',
  },
  notification: {
    notifications: 'اعلان‌ها',
    notificationSettings: 'تنظیمات اعلان‌ها',
    budgetAlerts: 'هشدارهای بودجه',
    goalAlerts: 'هشدارهای هدف',
    transactionNotifications: 'اعلان‌های تراکنش',
    transferNotifications: 'اعلان‌های انتقال',
    systemNotifications: 'اعلان‌های سیستم',
    pushNotifications: 'اعلان‌های فشاری',
    investmentGoalMilestone: 'دستاورد هدف سرمایه‌گذاری',
    investmentGoalCompleted: 'هدف سرمایه‌گذاری تکمیل شد',
    portfolioMovement: 'تغییر پرتفوی',
    dividendReceived: 'دریافت سود',
    unrealizedLoss: 'زیان غیرحققی',
    unrealizedGain: 'سود غیرحققی',
  },
  analytics: {
    analytics: 'تحلیل‌ها',
    overview: 'نمای کلی',
    income: 'درآمد',
    expenses: 'هزینه‌ها',
    netCashFlow: 'جریان نقدی خالص',
    trends: 'روندها',
    categories: 'دسته‌بندی‌ها',
    budgetPerformance: 'عملکرد بودجه',
    goalProgress: 'پیشرفت هدف',
  },
  investment: {
    investments: 'سرمایه‌گذاری',
    dashboard: 'داشبورد سرمایه‌گذاری',
    portfolio: 'پرتفوی سرمایه‌گذاری',
    totalValue: 'ارزش کل',
    totalInvested: 'کل سرمایه‌گذاری شده',
    cash: 'نقدین',
    cashBalance: 'موجودی نقدی',
    return: 'بازده',
    returnPercentage: 'درصد بازده',
    holdings: 'مالکیت‌ها',
    asset: 'دارایی',
    quantity: 'مقدار',
    averagePrice: 'قیمت متوسط',
    currentPrice: 'قیمت فعلی',
    previousPrice: 'قیمت قبلی',
    marketValue: 'ارزش بازار',
    pl: 'سود/زیان',
    unrealizedPL: 'سود/زیان غیرحققی',
    performance: 'عملکرد',
    allocation: 'تخصیص',
    accounts: 'حساب‌های سرمایه‌گذاری',
    accountNumber: 'شماره حساب',
    broker: 'کارگزاری',
    brokerName: 'نام کارگزاری',
    accountType: 'نوع حساب',
    baseCurrency: 'ارز پایه',
    status: 'وضعیت',
    active: 'فعال',
    suspended: 'معلیق',
    closed: 'بسته',
    transactions: 'تراکنش‌ها',
    transactionType: 'نوع تراکنش',
    fees: 'کارکرد',
    date: 'تاریخ',
    watchlists: 'فهرست‌های نظارت',
    watchlist: 'فهرست نظارت',
    addAsset: 'افزودن دارایی',
    removeAsset: 'حذف دارایی',
    createWatchlist: 'ایجاد فهرست نظارت',
    renameWatchlist: 'تغییر نام فهرست',
    dailyChange: 'تغییر روزانه',
    assetAllocation: 'تخصیص دارایی',
    accountAllocation: 'تخصیص حساب',
    today: 'امروز',
    noHoldings: 'هیچ مالکیتی وجود ندارد',
    noTransactions: 'هیچ تراکنشی وجود ندارد',
    noWatchlists: 'هیچ فهرست نظارتی وجود ندارد',
    name: 'نام',
    dividendReceived: 'سود دریافتی',
    portfolioMovement: 'تغییر پرتفوی',
    significantLoss: 'زیان قابل توجه',
    significantGain: 'سود قابل توجه',
    stock: 'سهام',
    etf: 'صندوق بورسی',
    bond: 'اوراق مشارکت',
    mutualFund: 'صندوق سرمایه‌گذاری',
    crypto: 'رمزارز',
    other: 'سایر',
    symbol: 'نماد',
    exchange: 'بازار',
  },
  payment: {
    payments: 'پرداخت‌ها',
    payment: 'پرداخت',
    type: 'نوع',
    status: 'وضعیت',
    amount: 'مبلغ',
    fees: 'کارکرد',
    description: 'توضیحات',
    sourceAccount: 'حساب مبنا',
    destinationName: 'نام مقصد',
    destinationType: 'نوع مقصد',
    date: 'تاریخ',
    pending: 'در انتظار',
    processing: 'در پردازش',
    completed: 'تکمیل شده',
    failed: 'ناموفق',
    cancelled: 'لغو شده',
    reversed: 'برگشت داده شده',
    billPayment: 'پرداخت قبض',
    topUp: 'شارژ',
    domesticTransfer: 'انتقال داخلی',
    mobileTopup: 'شارژ موبایل',
    charity: 'خیریه',
    other: 'سایر',
    cancelPayment: 'لغو پرداخت',
    createPayment: 'ایجاد پرداخت',
    destinationValue: 'مقدار مقصد',
  },
  lending: {
    lending: 'وام‌دهی',
    loanProducts: 'محصولات وام',
    loanProduct: 'محصول وام',
    loanApplications: 'درخواست‌های وام',
    loanApplication: 'درخواست وام',
    loans: 'وام‌ها',
    loan: 'وام',
    myLoans: 'وام‌های من',
    creditProfile: 'پروفایل اعتباری',
    creditScore: 'امتیاز اعتباری',
    financialHealth: 'سلامت مالی',
    eligibility: 'صلاحیت وام',
    checkEligibility: 'بررسی صلاحیت',
    createApplication: 'درخواست وام',
    newApplication: 'درخواست جدید',
    loanAmount: 'مبلغ وام',
    duration: 'مدت',
    purpose: 'هدف',
    interestRate: 'نرخ بهره',
    totalPayable: 'کل قابل پرداخت',
    monthlyInstallment: 'قسط ماهانه',
    remainingBalance: 'موجودی باقی‌مانده',
    principal: 'اصل وام',
    status: 'وضعیت',
    active: 'فعال',
    completed: 'تکمیل شده',
    defaulted: 'پیش‌فرض',
    draft: 'پیش‌نویس',
    submitted: 'ارسال شده',
    underReview: 'در بررسی',
    approved: 'تایید شده',
    rejected: 'رد شده',
    makePayment: 'پرداخت',
    paymentHistory: 'تاریخچه پرداخت',
    installment: 'قسط',
    dueDate: 'تاریخ سررسید',
    paid: 'پرداخت شده',
    pending: 'در انتظار',
    overdue: 'معوق',
    partial: 'جزئی',
    score: 'امتیاز',
    band: 'باند',
    previousScore: 'امتیاز قبلی',
    riskLevel: 'سطح ریسک',
    lowRisk: 'ریسک پایین',
    mediumRisk: 'ریسک متوسط',
    highRisk: 'ریسک بالا',
    maxEligible: 'حداکثر قابل‌وصول',
    cancelled: 'لغو شده',
  },
};

export const en = {
  common: {
    appName: 'NovaBank',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    active: 'Active',
    cancelled: 'Cancelled',
    createdAt: 'Created',
    description: 'Description',
  },
  currency: {
    toman: 'Toman',
    rial: 'Rial',
    usd: 'USD',
    eur: 'EUR',
  },
  account: {
    accounts: 'Accounts',
    balance: 'Balance',
    type: 'Type',
    cash: 'Cash',
    bank: 'Bank',
    wallet: 'Wallet',
    credit: 'Credit',
  },
  bank: {
    banks: 'Banks',
    name: 'Bank Name',
  },
  auth: {
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    phone: 'Phone',
    password: 'Password',
  },
  budget: {
    budgets: 'Budgets',
    budget: 'Budget',
    amount: 'Amount',
    spent: 'Spent',
    remaining: 'Remaining',
    exceeded: 'Exceeded',
    monthly: 'Monthly',
    yearly: 'Yearly',
    weekly: 'Weekly',
    period: 'Period',
  },
  goal: {
    goals: 'Goals',
    goal: 'Goal',
    target: 'Target',
    progress: 'Progress',
    completed: 'Completed',
    remaining: 'Remaining',
    targetDate: 'Target Date',
  },
  notification: {
    notifications: 'Notifications',
    notificationSettings: 'Notification Settings',
    budgetAlerts: 'Budget Alerts',
    goalAlerts: 'Goal Alerts',
    transactionNotifications: 'Transaction Notifications',
    transferNotifications: 'Transfer Notifications',
    systemNotifications: 'System Notifications',
    pushNotifications: 'Push Notifications',
    investmentGoalMilestone: 'Investment Goal Milestone',
    investmentGoalCompleted: 'Investment Goal Completed',
    portfolioMovement: 'Portfolio Movement',
    dividendReceived: 'Dividend Received',
    unrealizedLoss: 'Unrealized Loss',
    unrealizedGain: 'Unrealized Gain',
  },
  analytics: {
    analytics: 'Analytics',
    overview: 'Overview',
    income: 'Income',
    expenses: 'Expenses',
    netCashFlow: 'Net Cash Flow',
    trends: 'Trends',
    categories: 'Categories',
    budgetPerformance: 'Budget Performance',
    goalProgress: 'Goal Progress',
  },
  investment: {
    investments: 'Investments',
    dashboard: 'Investment Dashboard',
    portfolio: 'Investment Portfolio',
    totalValue: 'Total Value',
    totalInvested: 'Total Invested',
    cash: 'Cash',
    cashBalance: 'Cash Balance',
    return: 'Return',
    returnPercentage: 'Return %',
    holdings: 'Holdings',
    asset: 'Asset',
    quantity: 'Quantity',
    averagePrice: 'Average Price',
    currentPrice: 'Current Price',
    previousPrice: 'Previous Price',
    marketValue: 'Market Value',
    pl: 'P/L',
    unrealizedPL: 'Unrealized P/L',
    performance: 'Performance',
    allocation: 'Allocation',
    accounts: 'Investment Accounts',
    accountNumber: 'Account Number',
    broker: 'Broker',
    brokerName: 'Broker Name',
    accountType: 'Account Type',
    baseCurrency: 'Base Currency',
    status: 'Status',
    active: 'Active',
    suspended: 'Suspended',
    closed: 'Closed',
    transactions: 'Transactions',
    transactionType: 'Transaction Type',
    fees: 'Fees',
    date: 'Date',
    watchlists: 'Watchlists',
    watchlist: 'Watchlist',
    addAsset: 'Add Asset',
    removeAsset: 'Remove Asset',
    createWatchlist: 'Create Watchlist',
    renameWatchlist: 'Rename Watchlist',
    dailyChange: 'Daily Change',
    assetAllocation: 'Asset Allocation',
    accountAllocation: 'Account Allocation',
    today: 'Today',
    noHoldings: 'No holdings found',
    noTransactions: 'No transactions found',
    noWatchlists: 'No watchlists found',
    name: 'Name',
    dividendReceived: 'Dividend Received',
    portfolioMovement: 'Portfolio Movement',
    significantLoss: 'Significant Loss',
    significantGain: 'Significant Gain',
    stock: 'Stock',
    etf: 'ETF',
    bond: 'Bond',
    mutualFund: 'Mutual Fund',
    crypto: 'Crypto',
    other: 'Other',
    symbol: 'Symbol',
    exchange: 'Exchange',
  },
  payment: {
    payments: 'Payments',
    payment: 'Payment',
    type: 'Type',
    status: 'Status',
    amount: 'Amount',
    fees: 'Fees',
    description: 'Description',
    sourceAccount: 'Source Account',
    destinationName: 'Destination Name',
    destinationType: 'Destination Type',
    date: 'Date',
    pending: 'Pending',
    processing: 'Processing',
    completed: 'Completed',
    failed: 'Failed',
    cancelled: 'Cancelled',
    reversed: 'Reversed',
    billPayment: 'Bill Payment',
    topUp: 'Top Up',
    domesticTransfer: 'Domestic Transfer',
    mobileTopup: 'Mobile Topup',
    charity: 'Charity',
    other: 'Other',
    cancelPayment: 'Cancel Payment',
    createPayment: 'Create Payment',
    destinationValue: 'Destination Value',
  },
  lending: {
    lending: 'Lending',
    loanProducts: 'Loan Products',
    loanProduct: 'Loan Product',
    loanApplications: 'Loan Applications',
    loanApplication: 'Loan Application',
    loans: 'Loans',
    loan: 'Loan',
    myLoans: 'My Loans',
    creditProfile: 'Credit Profile',
    creditScore: 'Credit Score',
    financialHealth: 'Financial Health',
    eligibility: 'Loan Eligibility',
    checkEligibility: 'Check Eligibility',
    createApplication: 'Create Application',
    newApplication: 'New Application',
    loanAmount: 'Loan Amount',
    duration: 'Duration',
    purpose: 'Purpose',
    interestRate: 'Interest Rate',
    totalPayable: 'Total Payable',
    monthlyInstallment: 'Monthly Installment',
    remainingBalance: 'Remaining Balance',
    principal: 'Principal',
    status: 'Status',
    active: 'Active',
    completed: 'Completed',
    defaulted: 'Defaulted',
    draft: 'Draft',
    submitted: 'Submitted',
    underReview: 'Under Review',
    approved: 'Approved',
    rejected: 'Rejected',
    makePayment: 'Make Payment',
    paymentHistory: 'Payment History',
    installment: 'Installment',
    dueDate: 'Due Date',
    paid: 'Paid',
    pending: 'Pending',
    overdue: 'Overdue',
    partial: 'Partial',
    score: 'Score',
    band: 'Band',
    previousScore: 'Previous Score',
    riskLevel: 'Risk Level',
    lowRisk: 'Low Risk',
    mediumRisk: 'Medium Risk',
    highRisk: 'High Risk',
    maxEligible: 'Max Eligible',
    cancelled: 'Cancelled',
  },
};

export type Locale = 'fa' | 'en';
export type TranslationKeys = typeof fa;