export const VALID_LOAN_TRANSITIONS: Record<string, string[]> = {
  APPROVED: ['ACTIVE', 'CANCELLED'],
  ACTIVE: ['COMPLETED', 'DEFAULTED', 'CANCELLED'],
  COMPLETED: [],
  DEFAULTED: ['CANCELLED'],
  CANCELLED: [],
};

export const TERMINAL_LOAN_STATES = ['COMPLETED', 'DEFAULTED', 'CANCELLED'];

export const VALID_INSTALLMENT_TRANSITIONS: Record<string, string[]> = {
  PENDING: ['DUE', 'CANCELLED'],
  DUE: ['PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED'],
  PARTIALLY_PAID: ['PAID', 'OVERDUE', 'CANCELLED'],
  PAID: [],
  OVERDUE: ['PAID', 'CANCELLED'],
  CANCELLED: [],
};

export const TERMINAL_INSTALLMENT_STATES = ['PAID', 'CANCELLED'];
